[build]
  base = "frontend"
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build && cd ../netlify/functions && npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm --prefix frontend run dev"
  port = 8888
  targetPort = 5173
  framework = "#custom"
  functions = "netlify/functions"

[context.dev.environment]
  DB_HOST = "localhost"
  DB_PORT = "5432"
  DB_NAME = "petcare_db"
  DB_USER = "postgres"
  DB_PASSWORD = "petcare_dev_2025"
  JWT_SECRET = "your_secret_key_here"
  FRONTEND_URL = "http://localhost:8888"
  NODE_ENV = "development"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200